package com.model;

/**
 * TbDetail generated by MyEclipse Persistence Tools
 */

public class TbDetailDto implements java.io.Serializable {

	// Fields

	private TbDetail tbDetail;

	public TbDetail getTbDetail() {
		return tbDetail;
	}

	public void setTbDetail(TbDetail tbDetail) {
		this.tbDetail = tbDetail;
	}
}