package com.model;

/**
 * TbDetail generated by MyEclipse Persistence Tools
 */

public class TbDetail implements java.io.Serializable {

	// Fields

	private String id;
	private String forumid;
	private String content;
	private String who;
	private String intime;

	// Constructors

	/** default constructor */
	public TbDetail() {
	}

	/** minimal constructor */
	public TbDetail(String forumid, String who) {
		this.forumid = forumid;
		this.who = who;
	}

	/** full constructor */
	public TbDetail(String forumid, String content, String who, String intime) {
		this.forumid = forumid;
		this.content = content;
		this.who = who;
		this.intime = intime;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getForumid() {
		return this.forumid;
	}

	public void setForumid(String forumid) {
		this.forumid = forumid;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getWho() {
		return this.who;
	}

	public void setWho(String who) {
		this.who = who;
	}

	public String getIntime() {
		return this.intime;
	}

	public void setIntime(String intime) {
		this.intime = intime;
	}

}