package com.model;

/**
 * TbForum generated by MyEclipse Persistence Tools
 */

public class TbForum implements java.io.Serializable {

	// Fields

	private String id;
	private String title;
	private String father;
	private String intime;

	// Constructors

	/** default constructor */
	public TbForum() {
	}

	/** minimal constructor */
	public TbForum(String title, String father) {
		this.title = title;
		this.father = father;
	}

	/** full constructor */
	public TbForum(String title, String father, String intime) {
		this.title = title;
		this.father = father;
		this.intime = intime;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getFather() {
		return this.father;
	}

	public void setFather(String father) {
		this.father = father;
	}

	public String getIntime() {
		return this.intime;
	}

	public void setIntime(String intime) {
		this.intime = intime;
	}

}