package com.model;

/**
 * TbForum generated by MyEclipse Persistence Tools
 */

public class TbForumDto implements java.io.Serializable {

	// Fields

	private TbForum tbForum;

	public TbForum getTbForum() {
		return tbForum;
	}

	public void setTbForum(TbForum tbForum) {
		this.tbForum = tbForum;
	}
}