package com.model;

import java.util.Date;

/**
 * TbGg generated by MyEclipse Persistence Tools
 */

public class TbGgDto implements java.io.Serializable {

	// Fields

	private TbGg tbGg;

	public TbGg getTbGg() {
		return tbGg;
	}

	public void setTbGg(TbGg tbGg) {
		this.tbGg = tbGg;
	}
	
}