package com.model;

import java.util.Date;

/**
 * TbGg generated by MyEclipse Persistence Tools
 */

public class TbGg implements java.io.Serializable {

	// Fields

	private String id;
	private String title;
	private String content;
	private String intime;

	// Constructors

	/** default constructor */
	public TbGg() {
	}

	/** minimal constructor */
	public TbGg(String id, String content) {
		this.id = id;
		this.content = content;
	}

	/** full constructor */
	public TbGg(String id, String title, String content, String intime) {
		this.id = id;
		this.title = title;
		this.content = content;
		this.intime = intime;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getIntime() {
		return this.intime;
	}

	public void setIntime(String intime) {
		this.intime = intime;
	}

	

}