package com.model;

import java.util.List;

/**
 * TbLine generated by MyEclipse Persistence Tools
 */

public class TbLineDto implements java.io.Serializable {

	// Fields

	private TbLine tbLine;
	//前台标记
	private String flag;
	
	//第一次要座的车
	private TbLine firstLine;
	//第二次要座的车
	private TbLine secondLine;
	
	//存放满足条件的起点list
	private List<TbLine> starts;
	
	//存放满足条件的终点list
	private List<TbLine> ends;
	
	//换乘站点
	private String change;

	public TbLine getTbLine() {
		return tbLine;
	}

	public void setTbLine(TbLine tbLine) {
		this.tbLine = tbLine;
	}

	public String getFlag() {
		return flag;
	}
	

	public TbLine getFirstLine() {
		return firstLine;
	}

	public void setFirstLine(TbLine firstLine) {
		this.firstLine = firstLine;
	}

	public TbLine getSecondLine() {
		return secondLine;
	}

	public void setSecondLine(TbLine secondLine) {
		this.secondLine = secondLine;
	}

	public List<TbLine> getStarts() {
		return starts;
	}

	public void setStarts(List<TbLine> starts) {
		this.starts = starts;
	}

	public List<TbLine> getEnds() {
		return ends;
	}

	public void setEnds(List<TbLine> ends) {
		this.ends = ends;
	}

	public String getChange() {
		return change;
	}

	public void setChange(String change) {
		this.change = change;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}
	
	
}