package com.model;

/**
 * TbLoad generated by MyEclipse Persistence Tools
 */

public class TbLoad implements java.io.Serializable {

	// Fields

	private String id;
	private String name;
	private String url;
	private String intime;

	// Constructors

	/** default constructor */
	public TbLoad() {
	}

	/** minimal constructor */
	public TbLoad(String name) {
		this.name = name;
	}

	/** full constructor */
	public TbLoad(String name, String url, String intime) {
		this.name = name;
		this.url = url;
		this.intime = intime;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getIntime() {
		return this.intime;
	}

	public void setIntime(String intime) {
		this.intime = intime;
	}

}