package com.model;

import com.util.Upload;

/**
 * TbLoad generated by MyEclipse Persistence Tools
 */

public class TbLoadDto implements java.io.Serializable {

	// Fields

	private TbLoad tbLoad;
	private Upload upload;

	public TbLoad getTbLoad() {
		return tbLoad;
	}

	public void setTbLoad(TbLoad tbLoad) {
		this.tbLoad = tbLoad;
	}

	public Upload getUpload() {
		return upload;
	}

	public void setUpload(Upload upload) {
		this.upload = upload;
	}
}