package com.model;

/**
 * TbManager generated by MyEclipse Persistence Tools
 */

public class TbManagerDto implements java.io.Serializable {

	// Fields

	private TbManager tbManager;

	public TbManager getTbManager() {
		return tbManager;
	}

	public void setTbManager(TbManager tbManager) {
		this.tbManager = tbManager;
	}

	
}