package com.model;

/**
 * TbMember generated by MyEclipse Persistence Tools
 */

public class TbMember implements java.io.Serializable {

	// Fields

	private String id;
	private String userName;
	private String trueName;
	private String passWord;
	private String address;
	private String email;

	// Constructors

	/** default constructor */
	public TbMember() {
	}

	/** minimal constructor */
	public TbMember(String id, String userName, String trueName,
			String passWord) {
		this.id = id;
		this.userName = userName;
		this.trueName = trueName;
		this.passWord = passWord;
	}

	/** full constructor */
	public TbMember(String id, String userName, String trueName,
			String passWord, String address, String email) {
		this.id = id;
		this.userName = userName;
		this.trueName = trueName;
		this.passWord = passWord;
		this.address = address;
		this.email = email;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getTrueName() {
		return this.trueName;
	}

	public void setTrueName(String trueName) {
		this.trueName = trueName;
	}

	public String getPassWord() {
		return this.passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}