package com.model;

/**
 * TbMessage generated by MyEclipse Persistence Tools
 */

public class TbMessageDto implements java.io.Serializable {

	private TbMessage tbMessage;

	public TbMessage getTbMessage() {
		return tbMessage;
	}

	public void setTbMessage(TbMessage tbMessage) {
		this.tbMessage = tbMessage;
	}
}