package com.model;

/**
 * TbMember generated by MyEclipse Persistence Tools
 */

public class TbMemberDto implements java.io.Serializable {

	// Fields

	private TbMember tbMember;

	public TbMember getTbMember() {
		return tbMember;
	}

	public void setTbMember(TbMember tbMember) {
		this.tbMember = tbMember;
	}
}