package com.model;

/**
 * TbMessage generated by MyEclipse Persistence Tools
 */

public class TbMessage implements java.io.Serializable {

	// Fields

	private String id;
	private String title;
	private String who;
	private String content;
	private String intime;
	private String reflex;
	private String renamea;

	// Constructors

	/** default constructor */
	public TbMessage() {
	}

	/** minimal constructor */
	public TbMessage(String title, String who, String content) {
		this.title = title;
		this.who = who;
		this.content = content;
	}

	/** full constructor */
	public TbMessage(String title, String who, String content, String intime,
			String reflex, String renamea) {
		this.title = title;
		this.who = who;
		this.content = content;
		this.intime = intime;
		this.reflex = reflex;
		this.renamea = renamea;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getWho() {
		return this.who;
	}

	public void setWho(String who) {
		this.who = who;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getIntime() {
		return this.intime;
	}

	public void setIntime(String intime) {
		this.intime = intime;
	}

	public String getReflex() {
		return this.reflex;
	}

	public void setReflex(String reflex) {
		this.reflex = reflex;
	}

	public String getRenamea() {
		return this.renamea;
	}

	public void setRenamea(String renamea) {
		this.renamea = renamea;
	}

}