package com.model;

/**
 * TbPic generated by MyEclipse Persistence Tools
 */

public class TbPicDto implements java.io.Serializable {

	// Fields

	private TbPic tbPic;

	public TbPic getTbPic() {
		return tbPic;
	}

	public void setTbPic(TbPic tbPic) {
		this.tbPic = tbPic;
	}
}